---
title: "Publications"
output: 
  html_document:
    #toc: true
    #toc_depth: 2
    #toc_float: true
    theme: cerulean

---
<style type="text/css">
h1.title {
  font-size: 30px;
}

h1 { /* Header 1 */
  font-size: 20px
}
</style>
***
# Original research papers

- Đoković J. B., Demisli S., Savić S. M., Savić S. R., Ranđelović D. V., Marković B. D., Pantelić I., Mitrović J. R., Stanković T., Papadimitrou V., Xenakis A., Savić S. D.. *Evaluation of PEGylation efficacy of curcumin-loaded nanoemulsions using complementary methods to assess protein interactions and physicochemical properties*. Journal of Molecular Liquids. 2024; 404: 124888. (Q1; M21 Pharmaceutics, IF 5.3)
https://doi.org/10.1016/j.molliq.2024.124888

- Mitrović J. R., Bjelošević Žiberna M., Vukadinović A., Knutson D. E., Sharmin D., Kremenović A., Ahlin Grabnar P., Planinšek O., Lunter D., Cook J. M., Savić M. M., Savić S. D.. *. Freeze-dried nanocrystal dispersion of novel deuterated pyrazoloquinolinone ligand (DK-I-56-1): Process parameters and lyoprotectant selection through the stability study*. European Journal of Pharmaceutical Sciences. 2023; 189: 106557. (Q1; M21 Pharmaceutics, IF 4.6)
https://doi.org/10.1016/j.ejps.2023.106557

- Mitrović J. R., Divović Matović B., Knutson D. E., Petković M., Djorovic Dj., Randjelović D. V., Dobričić V. D., Đoković J. B., Lunter D. J., Cook J. M., Savić M. M., Savić S. D.. *High amount of lecithin facilitates oral delivery of a poorly soluble pyrazoloquinolinone ligand formulated in lipid nanoparticles: Physicochemical, structural and pharmacokinetic performances*. International Journal of Pharmaceutics. 2023; 122613.(Q1; M21 Pharmaceutics, IF 6.51) https://doi.org/10.1016/j.ijpharm.2023.122613 

- Ilić T, Đoković JB, Nikolić I, Mitrović JR, Pantelić I, Savić SD, Savić MM. *Parenteral Lipid-Based Nanoparticles for CNS Disorders: Integrating Various Facets of Preclinical Evaluation towards More Effective Clinical Translation*. Pharmaceutics. 2023; 15(2):443.(Q1; M21 Pharmaceutics, IF 6.525) https://doi.org/10.3390/pharmaceutics15020443 

-  Divović Matović B, Knutson D, Mitrović J, Stevanović V, Stanojević B, Savić S, Cook J, Savić M. *Behavioural interaction of pyrazoloquinolinone positive allosteric modulators at α6GABAA receptors and diazepam in rats: Anti-diazepam-induced ataxia action as a structure-dependent feature*. Basic & Clinical Pharmacology & Toxicology. 2022; 1-11. (Q2; M22 Pharmacology & Pharmacy, IF 3.688) https://doi.org/10.1111/bcpt.13801

- Đoković JB, Demisli S, Savić SM, Marković BD, Cekić ND, Randjelovic DV, Mitrović JR, Lunter DJ, Papadimitriou V, Xenakis A, Savić SD. *The Impact of the Oil Phase Selection on Physicochemical Properties, Long-Term Stability, In Vitro Performance and Injectability of Curcumin-Loaded PEGylated Nanoemulsions*. Pharmaceutics. 2022 Aug 10;14(8):1666. (Q1; M21 Pharmaceutics, IF 6.525) https://doi.org/10.3390/pharmaceutics14081666 


- Bernardo, A., Lee, P., Marcotte, M., Mian, M.Y., Rezvanian, S., Sharmin, D., Kovačević, A., Savić, M.M., Cook, J.M., Sibille, E. and Prevot, T.D., 2022. *Symptomatic and neurotrophic effects of GABAA receptor positive allosteric modulation in a mouse model of chronic stress*. Neuropsychopharmacology, pp.1-12. (Q1; M21a Pharmacology & Pharmacy, IF 8.294) https://doi.org/10.1038/s41386-022-01360-y 

&nbsp; &nbsp; &nbsp; 

# Conference poster presentations

- [**The impact of the aqueous phase on the physicochemical characteristics of nanoemulsions loaded with patent protected compound GL-II-73**](https://farfar.pharmacy.bg.ac.rs/handle/123456789/5575)

   Autori: Đoković, Jelena; Nikolić, Ines; Sharmin, Dishary; Cook, James M.; Savić, Miroslav; Borchard, Gerrit; Savić, Snežana
   
   14th World Meeting on Pharmaceutics, Biopharmaceutics and Pharmaceutical Technology, 18 - 21 March 2024, Vienna, Austria

- [**Overcoming the low solubility of novel pyrazoloquinolinone ligand (CW-02-79) by combination of drugphospholipid complex and nanoemulsion technology: design and physicochemical evaluation**](https://farfar.pharmacy.bg.ac.rs/handle/123456789/5578)

   Autori: Stanković, Tijana; Ilić, Tanja; Petković, Miloš; Pantelić, Ivana; Dobričić, Vladimir; Cook, James M.; Savić, Miroslav; Savić, Snežana
   
   14th World Meeting on Pharmaceutics, Biopharmaceutics and Pharmaceutical Technology, 18 - 21 March 2024, Vienna, Austria

- [**Sizing up the nanomedicines: a thorough examination of techniques and data interpretation**](https://sfnanocongres.fr/)

   Autori: Nikolić, Ines; Đoković, Jelena; Mehn, Dora; Guerrini, Giuditta; Colpo, Pascal; Jordan, Olivier; Savić, Snežana; Borchard, Gerit
   
   SFNano Conference, 4 - 6 December 2023, Montpellier, France

- [**Deciphering ciprofloxacin-induced neurotoxicity: behavioral and molecular profiling of ciprofloxacin treatment in rats**](Deciphering ciprofloxacin induced neurotoxicity behavioral and molecular profiling of ciprofloxacin treatment in rats.pdf)

   Autori: Mirković, Kristina; Aranđelović, Jovana; Kojić, Jana; Stevanović, Vladimir; Batinić, Bojan; Todorović, Vanja; Đoković, Jelena; Santrač, Anja; Major, Tamara; Savić, Miroslav
   
   36th ECNP Congress, 7 - 10 October 2023, Barselona, Spain
   
- [**Estimation of endotoxin level in nanocrystal dispersion of DK-I-56-1 intended for parenteral administration**](Estimation of endotoxin level in nanocrystal dispersion of DK-I-56-1 intended for parenteral administration.pdf)

   Autori: Mitrović, Jelena; Ilić, Tanja; Jančić, Ivan; Bufan, Biljana; Savić, Miroslav; Savić, Snežana
   
   NANOGVA Symposium, 5 - 6 October 2023, Geneva, Switzerland

- [**Reward-related impulsivity as a possible surrogate marker of motivation in aging Sprague-Dawley rats**](Reward related impulsivity as a possible surrogate marker of motivation in aging Sprague Dawley rats.pdf)

   Autori: Aranđelović, Jovana; Kojić, Jana; Mirković, Kristina; Jančić, Ivan; Todorović, Lidija; Savić, Miroslav
   
   36th ECNP Congress, 7 - 10 October 2023, Barselona, Spain

- [**Systemic inflammation followed by chronic unpredictable stress in rats: the model of “binge-drinking” of sucrose solution**](Systemic inflammation followed by chronic unpredictable stress in rats the model of binge drinking of sucrose solution.pdf)

   Autori: Aranđelović, Jovana; Kojić, Jana; Batinić, Bojan; Divović Matović, Branka; Mirković, Kristina; Santrač, Anja; Savić, Miroslav
   
   11th IBRO World Congress of Neuroscience in Granada, 9 - 13 September 2023, Granada, Spain

- [**Preformulation and development of preliminary nanoemulsion carrier for patent protected compound GL-II-73**](Preformulation and development of preliminary nanoemulsion carrier for patent protected compound GLII73.pdf)

   Autori: Đoković, Jelena; Marković, Bojan; Sharmin, Dishary; Cook, James M; Savić, Miroslav; Savić, Snežana
   
   14th Central European Symposium on Pharmaceutical Technology, 28 - 30 September 2023, Ohrid, North Macedonia

- [**Design of tailor-made biocompatible nanocarrier for novel pyrazoloquinolinone ligand (CW-02-79) based on comprehensive evaluation of critical physicochemical descriptors**](Design of tailor made biocompatible nanocarrier for novel pyrazoloquinolinone ligand.pdf)

   Autori: Stanković, Tijana; Ilić, Tanja; Pantelić, Ivana; Tošić, Anđela; Mitrović, Jelena; Cook, James M; Savić, Miroslav; Savić, Snežana
   
   10th IAPC Meeting. Tenth World Conference on Physico-Chemical Methods in Drug Discovery & Sixth World Conference on ADMET and DMPK, 4 - 6 September 2023, Belgrade, Serbia

- [**Searching for the best way to incorporate the proprietary compound GL-II -73 into the nanoemulsion carrier for prospective parenteral application**](Searching for the best way to incorporate the proprietary compound GLII73.pdf)

   Autori: Đoković, Jelena; Marković, Bojan; Sharmin, Dishary; Cook, James M; Savić, Miroslav; Savić, Snežana
   
   10th IAPC Meeting. Tenth World Conference on Physico-Chemical Methods in Drug Discovery & Sixth World Conference on ADMET and DMPK, 4 - 6 September 2023, Belgrade, Serbia

- [**Navigating towards improved cytotoxicity assessment in nanomedicine development: Shifting from colorimetric to fluorescence-based assays**](Navigating towards improved cytotoxicity assessment in nanomedicine development.pdf)

   Autori: Nikolić, Ines; Petrović, Marija; Mitrović, Jelena; Sublet, Emmanuelle; Jordan, Olivier; Savić, Snežana; Borchard, Gerrit
   
   10th IAPC Meeting. Tenth World Conference on Physico-Chemical Methods in Drug Discovery & Sixth World Conference on ADMET and DMPK, 4 - 6 September 2023, Belgrade, Serbia

- [**Neuropharmacokinetics: the secret life of - old and novel - psychopharmacological drugs**](Neuropharmacokinetics Miroslav Savic.pdf)

   Autori: Savić, Miroslav
   
   10th IAPC Meeting. Tenth World Conference on Physico-Chemical Methods in Drug Discovery & Sixth World Conference on ADMET and DMPK, 4 - 6 September 2023, Belgrade, Serbia

- [**Sizing experiments and bio-nano interactions: method matters**](Sizing experiments and bio nano interactions_method matters.pdf)

   Authors: Nikolić, Ines; Petrović, Marija; Krupnik, Leonard; Randjelovic, Danijela; Avaro, Jonathan; Neels, Antonia; Borhard, Gerrit; Jordan, Olivier; Đoković, Jelena; Savić, Snežana
   
   4th European Conference on Pharmaceutics, 20 - 21 March 2023, Marseille, France

- [**Biocompatible nanoemulsions as a tool for preclinical testing of CW-02-79, a pyrazoloquinolinone modulator of sigma-2 receptors: preformulation and formulation studies**](Biocompatible nanoemulsions as a tool for preclinical testing of CW_02_79.pdf)

   Authors: Ilić, Tanja; Stanković, Tijana; Mitrović, Jelena; Pantelić, Ivana; Dobričić, Vladimir; Cook, James M.; Savić, Miroslav; Savić, Snežana
   
   4th European Conference on Pharmaceutics, 20 - 21 March 2023, Marseille, France


- [**Structural analysis of PEGylated nanoemulsions using EPR spectroscopy – the impact of an active compound incorporated in stabilizing layer**](Structural analysis of PEGylated nanoemulsions using EPR spectroscopy.pdf)

   Authors: Đoković, Jelena; Demisli, Sotiria; Papadimitriou, Vassiliki; Savić, Snežana
   
   4th European Conference on Pharmaceutics, 20 - 21 March 2023, Marseille, France

- [**Neuroimmune aspects of mood, anxiety and cognitive effects of leads/drug candidates acting at GABAA and/or sigma-2 receptors: In vitro/in vivo delineation by nano- and hiPSC-based platforms**](Neuroimmune aspects of mood, anxiety and cognitive effects of leads drug candidates acting at GABAA and or sigma2 receptors - Apstract.pdf) - [*presentation*](Neuroimmune aspects of mood, anxiety and cognitive effects of leads drug candidates acting at GABAA and or sigma2 receptors.pdf)

   Authors: Savić, Snežana; Pantelić, Ivana; Jančić, Ivan; Savić, Miroslav
   
   8th Congress of Pharmacists of Serbia, 12.-15. October 2022, Belgrade, Serbia


- [**Investigation of albumin adsorption on DK-I-56-1 nanocrystals by dynamic light scattering**](Investigation of albumin adsorption on DK-I-56-1 nanocrystals by dynamic light scattering.pdf)

   Authors: Mitrović, Jelena; Knutson, Daniel; Nikolić, Ines; Cook, James; Savić, Miroslav; Savić, Snežana
   
   8th Congress of Pharmacists of Serbia, 12.-15. October 2022, Belgrade, Serbia


- [**Analyzing the impact of the oil phase selection and curcumin presence on the nanoemulsion stabilizing layer using electron paramagnetic resonance spectroscopy**](Analyzing the impact of the oil phase selection and curcumin presence on the nanoemulsion stabilizing layer using electron paramagnetic resonance spectroscopy.pdf)

   Authors: Đoković, Jelena; Demisli, Sotiria; Papadimitriou, Vassiliki; Xenakis, Aristotelis; Savić, Snežana
   
   8th Congress of Pharmacists of Serbia, 12.-15. October 2022, Belgrade, Serbia

- [**A proposal of innovative injectability assessment method for intravenous formulations - case study on PEGylated nanoemulsions**](A proposal of innovative injectability assessment method for intravenous formulations - case study on PEGylated nanoemulsions.pdf)

   Authors: Đoković, Jelena; Savić, Sanela; Cekić, Nebojša; Savić, Snežana
   
   9th BBBB International conference on pharmaceutical sciences, 15 - 17 September 2022, Ljubljana, Slovenia

- [**Freeze-dried nanocrystal dispersion of novel deuterated pyrazoloquinolinone ligand (DK-I-56-1); process parameters and cryoprotectant selection through stability study**](Freeze-dried nanocrystal dispersion of novel deuterated pyrazoloquinolinone ligand (DK-I-56-1); process parameters and cryoprotectant selection through stability study.pdf)

   Authors: Mitrović, Jelena; Bjelošević, Maja; Knutson, Daniel E.; Kremenović, Aleksandar; Lunter, Dominique; Ahlin Grabnar, Pegi; Cook, James M.; Savić, Miroslav M.; Savić, Snežana D.
   
   9th BBBB International conference on pharmaceutical sciences, 15 - 17 September 2022, Ljubljana, Slovenia


- [**Physicochemical/structural investigation of lipid nanoparticles with high lecithin amounts loaded with patent protected pyrazoloquinolinone ligand DK-I-60-3**](Physicochemical structural investigation of lipid nanoparticles with high lecithin amounts loaded with patent protected pyrazoloquinolinone ligand DK-I-60-3.pdf)

   Authors: Mitrović, Jelena; Petković, Miloš; Ranđelović, Danijela; Đoković, Jelena; Knutson, Daniel; Cook, James; Savić, Vladimir; Savić, Miroslav; Savić, Snežana 

   13th World meeting on pharmaceutics, biopharmaceutics and pharmaceutical technology, 28-31 March 2022, Rotterdam, Netherlands