---
title: "Toolbox"
#runtime: shiny
output: 
  html_document:
    #toc: true
    #toc_depth: 2
    #toc_float: true
    theme: cerulean
    

---
<style type="text/css">
h1.title {
  font-size: 30px;
}

h1 { /* Header 1 */
  font-size: 20px
}
</style>
***

Results obtained during the NanoCellEmoCog project, funded by the Science fund of the Republic of Serbia, enabled creation of the following toolbox for determining the optimal lipide nanoformulation type for hits / leads / drug candidates (DC) / active pharmaceutical ingredients (API)  poorly soluble in water. Although the toolbox may be of interest for researchers developing formulations for other routes of administration, it is particularly designed for parenteral formulations.

&NewLine;
&NewLine;

<iframe height="400" width="100%" frameborder="no" src="https://nanocellemocog.shinyapps.io/my_app_en/"> </iframe>

&NewLine;
&NewLine;

\* Note:

1. It is necessary to determine the solubility of the substance (Hits / Leads / Drug Candidates (DC) / Active Pharmaceutical Ingredients (API)) in oils that have the status of pharmaceutical excipients authorised for parenteral/oral administration (e.g. soybean oil, castor oil, medium-chain triglycerides), individually or in mixtures (usual ratios of medium- and long-chain triglycerides 1:1, 2:1 or 4:1, w/w), in order to select the optimal composition of the oil phase.

2. If sufficient solubility in oils is not achieved, solid amphiphilic lipids can be added to the mixture (e.g. lecithin/oil in a ratio of 1:10).

3. With a oil phase content of 20 % in the final formulation, the required minimum solubility of the test substance in oils is usually around 7.5 mg/ml, which corresponds to a minimum concentration of the substance in the formulation of 1.5 mg/ml, and relates to the dosing regimen in preclinical pharmacodynamic and pharmacokinetic studies of drug candidates (parenteral and oral routes of administration).

&NewLine;
&NewLine;

For additional information see the [published results](https://nanocellemocog.github.io/NanoCellEmoCogEngl/publications_en.html) within the project or [contact](https://nanocellemocog.github.io/NanoCellEmoCogEngl/contact_en.html) the NanoCellEmoCog team.